name: "Pull Request: Validate"

on:
    pull_request:
        types: [ opened, edited, synchronize, labeled, unlabeled ]

jobs:
    validate:
        name: Validate pull request
        runs-on: ubuntu-latest
        permissions:
            contents: read
            issues: read
            pull-requests: read
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Validate
                uses: ./
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
